import { EDGE_FUNCTIONS_URL } from '@/lib/constants'
import type { CreateLessonRequest } from '@/types/api'
import type { Lesson } from '@/types/lesson'

/**
 * Calls the create-lesson-from-change Edge Function.
 * Sends a diff summary, error log, or notes and receives a structured lesson
 * generated by Gemini AI.
 */
export async function createLessonFromChange(
  request: CreateLessonRequest
): Promise<Lesson> {
  const res = await fetch(`${EDGE_FUNCTIONS_URL}/create-lesson-from-change`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(request),
  })

  if (!res.ok) {
    const text = await res.text()
    throw new Error(`Create lesson failed (${res.status}): ${text}`)
  }

  return res.json() as Promise<Lesson>
}
